import 'dotenv/config';
import mongoose from 'mongoose';
import { connectDB } from '../config/db.js';
import Persona from '../models/persona.model.js';

// Arcanos simplificados para la demo, no pretenden ser 100% canónicos.
// Retratos vía megamitensei.fandom.com (misma wiki de la que salen los emblemas de arcanos).
const personas = [
  { nombre: 'Orpheus', arcana: 'Fool', nivel: 1,
    stats: { fuerza: 4, magia: 5, resistencia: 4, agilidad: 2, suerte: 2 },
    habilidades: ['Agi', 'Dia'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/b/bb/Orpheus_Render.png/revision/latest?cb=20230302222401' },
  { nombre: 'Izanagi', arcana: 'Fool', nivel: 8,
    stats: { fuerza: 7, magia: 7, resistencia: 6, agilidad: 9, suerte: 6 },
    habilidades: ['Zio', 'Cleave'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/e/ec/IzanagiP4Full.png/revision/latest?cb=20230818092237' },
  { nombre: 'Arsène', arcana: 'Fool', nivel: 6,
    stats: { fuerza: 6, magia: 6, resistencia: 4, agilidad: 9, suerte: 4 },
    habilidades: ['Eiha', 'Cleave'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/1/19/Arsene.png/revision/latest?cb=20170612163748' },
  { nombre: 'Pixie', arcana: 'Lovers', nivel: 2,
    stats: { fuerza: 1, magia: 7, resistencia: 3, agilidad: 5, suerte: 4 },
    habilidades: ['Dia', 'Zio'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/3/30/MT2_Pixie.png/revision/latest?cb=20231120092123' },
  { nombre: 'Jack Frost', arcana: 'Magician', nivel: 5,
    stats: { fuerza: 3, magia: 9, resistencia: 3, agilidad: 5, suerte: 8 },
    habilidades: ['Bufu', 'Mabufu'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/e/e6/00072_Jack_Frost.png/revision/latest?cb=20220727075637' },
  { nombre: 'Angel', arcana: 'Priestess', nivel: 4,
    stats: { fuerza: 3, magia: 8, resistencia: 5, agilidad: 5, suerte: 5 },
    habilidades: ['Dia', 'Media'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/f/f2/00029_Angel_%28Reupload%29.png/revision/latest?cb=20220525024440' },
  { nombre: 'Titania', arcana: 'Empress', nivel: 15,
    stats: { fuerza: 7, magia: 14, resistencia: 11, agilidad: 9, suerte: 11 },
    habilidades: ['Media', 'Garula'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/f/fb/00303_Titania.png/revision/latest?cb=20221116132051' },
  { nombre: 'Cerberus', arcana: 'Chariot', nivel: 10,
    stats: { fuerza: 12, magia: 3, resistencia: 9, agilidad: 11, suerte: 5 },
    habilidades: ['Agi', 'Rampage'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/1/1b/Cerberus_%28MT_Art%29.png/revision/latest?cb=20210802021711' },
  { nombre: 'Mothman', arcana: 'Hermit', nivel: 18,
    stats: { fuerza: 10, magia: 14, resistencia: 10, agilidad: 16, suerte: 8 },
    habilidades: ['Bufula', 'Dodge'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/e/e0/Mothmanof.png/revision/latest?cb=20210912210516' },
  { nombre: 'Yoshitsune', arcana: 'Star', nivel: 42,
    stats: { fuerza: 28, magia: 14, resistencia: 19, agilidad: 33, suerte: 21 },
    habilidades: ['Hassou Tobi', 'Brave Blade'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/b/bf/Yoshitsune_DevSum.png/revision/latest?cb=20231202235420' },
  { nombre: 'Thor', arcana: 'Emperor', nivel: 25,
    stats: { fuerza: 19, magia: 19, resistencia: 15, agilidad: 13, suerte: 10 },
    habilidades: ['Ziodyne', 'Thunder Reign'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/2/22/00007_Thor_%28Reupload%29.png/revision/latest?cb=20220525024430' },
  { nombre: 'Satan', arcana: 'Judgement', nivel: 90,
    stats: { fuerza: 54, magia: 54, resistencia: 51, agilidad: 36, suerte: 36 },
    habilidades: ['Megidolaon', 'Judgement Light'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/f/fb/Satan_MT_II.png/revision/latest?cb=20231124025321' },

  // --- Segunda tanda: más Personas repartidas por los 22 arcanos ---
  { nombre: 'Forneus', arcana: 'Magician', nivel: 12,
    stats: { fuerza: 4, magia: 16, resistencia: 6, agilidad: 10, suerte: 8 },
    habilidades: ['Bufu', 'Mind Charge'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/4/4a/00086_Forneus.png/revision/latest?cb=20220731054145' },
  { nombre: 'Ara Mitama', arcana: 'Priestess', nivel: 7,
    stats: { fuerza: 2, magia: 12, resistencia: 4, agilidad: 5, suerte: 9 },
    habilidades: ['Dia', 'Enduring Soul'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/f/f7/Ara_Mitama_%28Devil_Summoner_Art%29.png/revision/latest?cb=20240416031913' },
  { nombre: 'Kikuri-Hime', arcana: 'Empress', nivel: 20,
    stats: { fuerza: 8, magia: 19, resistencia: 13, agilidad: 8, suerte: 15 },
    habilidades: ['Mediarama', 'Samarecarm'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/3/33/00009_Kikuri-hime_%28Reupload%29.png/revision/latest?cb=20220525024457' },
  { nombre: 'Odin', arcana: 'Emperor', nivel: 35,
    stats: { fuerza: 25, magia: 22, resistencia: 20, agilidad: 17, suerte: 15 },
    habilidades: ['Thunder Reign', 'Ziodyne'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/f/f5/Odin_%28MTII_Art%29.png/revision/latest?cb=20240627095126' },
  { nombre: 'Ganesha', arcana: 'Hierophant', nivel: 22,
    stats: { fuerza: 14, magia: 19, resistencia: 16, agilidad: 7, suerte: 12 },
    habilidades: ['Garudyne', 'Mind Charge'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/d/d5/00052_Ganesha.png/revision/latest?cb=20220722052205' },
  { nombre: 'Anubis', arcana: 'Hierophant', nivel: 24,
    stats: { fuerza: 21, magia: 12, resistencia: 16, agilidad: 14, suerte: 9 },
    habilidades: ['Diarahan', 'Vorpal Blade'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/d/d3/SMT_II_Anubis.png/revision/latest?cb=20240502075350' },
  { nombre: 'Andras', arcana: 'Lovers', nivel: 14,
    stats: { fuerza: 12, magia: 7, resistencia: 9, agilidad: 14, suerte: 7 },
    habilidades: ['Brutal Slash', 'Fear Boost'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/a/a2/00089_Andras.png/revision/latest?cb=20220731054149' },
  { nombre: 'Take-Minakata', arcana: 'Chariot', nivel: 27,
    stats: { fuerza: 24, magia: 7, resistencia: 18, agilidad: 20, suerte: 11 },
    habilidades: ['Assault Dive', 'Rampage'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/e/e5/00460_Takeminakata.png/revision/latest?cb=20220827150731' },
  { nombre: 'Ose', arcana: 'Justice', nivel: 16,
    stats: { fuerza: 12, magia: 12, resistencia: 10, agilidad: 10, suerte: 8 },
    habilidades: ['Confuse Boost', 'Panic Voice'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/2/28/Ose_%28Dx2_Art%29.png/revision/latest?cb=20210705093954' },
  { nombre: 'Vishnu', arcana: 'Justice', nivel: 55,
    stats: { fuerza: 35, magia: 37, resistencia: 29, agilidad: 23, suerte: 23 },
    habilidades: ['Divine Judgement', 'Salvation'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/f/f3/Vishnu_%28MTII_Art%29.png/revision/latest?cb=20240617092254' },
  { nombre: 'Berith', arcana: 'Hermit', nivel: 13,
    stats: { fuerza: 12, magia: 10, resistencia: 8, agilidad: 10, suerte: 6 },
    habilidades: ['Agilao', 'Tarukaja'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/b/ba/00085_Berith.png/revision/latest?cb=20220731054145' },
  { nombre: 'Norn', arcana: 'Fortune', nivel: 30,
    stats: { fuerza: 12, magia: 24, resistencia: 15, agilidad: 15, suerte: 22 },
    habilidades: ['Luck Boost', 'Debilitate'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/e/e4/Norn_%28Dx2_Art%29.png/revision/latest?cb=20220302084901' },
  { nombre: 'Fortuna', arcana: 'Fortune', nivel: 18,
    stats: { fuerza: 6, magia: 14, resistencia: 8, agilidad: 12, suerte: 19 },
    habilidades: ["Lucky Sweep", "Fortune's Favor"],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/1/17/SH_Fortuna.png/revision/latest?cb=20240525135047' },
  { nombre: 'Rangda', arcana: 'Strength', nivel: 45,
    stats: { fuerza: 32, magia: 32, resistencia: 23, agilidad: 21, suerte: 14 },
    habilidades: ['Megidola', 'Curse Boost'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/f/f3/RangdaSMT2.jpg/revision/latest?cb=20080807180310' },
  { nombre: 'Thoth', arcana: 'Strength', nivel: 33,
    stats: { fuerza: 17, magia: 30, resistencia: 17, agilidad: 15, suerte: 15 },
    habilidades: ['Wisdom Wave', 'Mabufula'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/a/a1/NINE_Thoth.png/revision/latest?cb=20240620111954' },
  { nombre: 'Mokoi', arcana: 'HangedMan', nivel: 9,
    stats: { fuerza: 7, magia: 8, resistencia: 5, agilidad: 10, suerte: 7 },
    habilidades: ['Poison Breath', 'Sukukaja'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/0/08/Mokoi.png/revision/latest?cb=20240416030710' },
  { nombre: 'Alice', arcana: 'Death', nivel: 40,
    stats: { fuerza: 8, magia: 40, resistencia: 13, agilidad: 19, suerte: 32 },
    habilidades: ['Die For Me!', 'Mamudoon'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/f/f7/Smtalice.png/revision/latest?cb=20220227155358' },
  { nombre: 'Matador', arcana: 'Death', nivel: 20,
    stats: { fuerza: 15, magia: 10, resistencia: 11, agilidad: 17, suerte: 10 },
    habilidades: ['Brave Blade', 'Charge'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/0/04/Matador_%28SMT_Art%29.png/revision/latest?cb=20210912215030' },
  { nombre: 'Yatagarasu', arcana: 'Temperance', nivel: 17,
    stats: { fuerza: 12, magia: 12, resistencia: 10, agilidad: 14, suerte: 10 },
    habilidades: ['Garula', 'Trafuri'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/0/0b/00037_Yatagarasu.png/revision/latest?cb=20220720103451' },
  { nombre: 'Ame-no-Uzume', arcana: 'Temperance', nivel: 15,
    stats: { fuerza: 7, magia: 13, resistencia: 7, agilidad: 11, suerte: 13 },
    habilidades: ['Dance of Delusion', 'Charm Boost'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/5/57/00010_Ame-no-Uzume_%28Reupload%29.png/revision/latest?cb=20220525024430' },
  { nombre: 'Astaroth', arcana: 'Devil', nivel: 38,
    stats: { fuerza: 28, magia: 28, resistencia: 23, agilidad: 13, suerte: 13 },
    habilidades: ['Megido', 'Poison Breath'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/0/0a/Astaroth_%28MTII_Art%29.png/revision/latest?cb=20231123060845' },
  { nombre: 'Belial', arcana: 'Devil', nivel: 42,
    stats: { fuerza: 32, magia: 32, resistencia: 24, agilidad: 16, suerte: 13 },
    habilidades: ['Maeigaon', 'Curse Breath'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/3/3a/Belial_MTII.png/revision/latest?cb=20231201065732' },
  { nombre: 'Setanta', arcana: 'Tower', nivel: 19,
    stats: { fuerza: 17, magia: 6, resistencia: 11, agilidad: 19, suerte: 8 },
    habilidades: ['Brutal Slash', 'Rakukaja'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/4/4c/Setanta_%28Dx2%29.png/revision/latest?cb=20230622071653' },
  { nombre: 'Nebiros', arcana: 'Tower', nivel: 26,
    stats: { fuerza: 21, magia: 19, resistencia: 16, agilidad: 12, suerte: 9 },
    habilidades: ['Curse Boost', 'Mudoon'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/2/28/00080_Nebiros.png/revision/latest?cb=20220731054145' },
  { nombre: 'Cu Chulainn', arcana: 'Star', nivel: 31,
    stats: { fuerza: 24, magia: 11, resistencia: 16, agilidad: 24, suerte: 13 },
    habilidades: ['Vorpal Blade', 'Brave Blade'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/1/1a/00066_Cu_Chulainn.png/revision/latest?cb=20220727075630' },
  { nombre: 'Queen Mab', arcana: 'Moon', nivel: 23,
    stats: { fuerza: 11, magia: 22, resistencia: 11, agilidad: 13, suerte: 13 },
    habilidades: ['Mabufula', 'Marin Karin'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/c/cb/Queen_Medb.png/revision/latest?cb=20240515042730' },
  { nombre: 'Black Frost', arcana: 'Moon', nivel: 28,
    stats: { fuerza: 13, magia: 23, resistencia: 11, agilidad: 17, suerte: 17 },
    habilidades: ['Mabufula', 'Ice Amp'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/d/da/00499_Black_Frost.png/revision/latest?cb=20220822115856' },
  { nombre: 'Amaterasu', arcana: 'Sun', nivel: 50,
    stats: { fuerza: 26, magia: 37, resistencia: 29, agilidad: 19, suerte: 24 },
    habilidades: ['Judgement Light', 'Salvation'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/8/8b/Amateratsu.jpg/revision/latest?cb=20080806033633' },
  { nombre: 'Michael', arcana: 'Judgement', nivel: 60,
    stats: { fuerza: 37, magia: 40, resistencia: 34, agilidad: 26, suerte: 23 },
    habilidades: ['Megidolaon', 'Divine Shot'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/c/ce/00021_Michael.png/revision/latest?cb=20220530041014' },
  { nombre: 'Lucifer', arcana: 'World', nivel: 99,
    stats: { fuerza: 58, magia: 58, resistencia: 52, agilidad: 45, suerte: 39 },
    habilidades: ['Morning Star', 'Grace of Ruin'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/d/dd/Lucifer_MTII.png/revision/latest?cb=20231201055634' },
];

async function seed() {
  await connectDB();
  await Persona.deleteMany({});
  await Persona.insertMany(personas);
  console.log(`[seed] ${personas.length} Personas insertadas`);
  await mongoose.disconnect();
}

seed().catch((err) => {
  console.error('[seed] error:', err);
  process.exit(1);
});
