import 'dotenv/config';
import mongoose from 'mongoose';
import { connectDB } from '../config/db.js';
import Persona from '../models/persona.model.js';

// Arcanos simplificados para la demo, no pretenden ser 100% canónicos.
// Retratos vía megamitensei.fandom.com (misma wiki de la que salen los emblemas de arcanos).
const personas = [
  { nombre: 'Orpheus', arcana: 'Fool', nivel: 1,
    stats: { fuerza: 4, magia: 5, resistencia: 4, agilidad: 2, suerte: 2 },
    habilidades: ['Agi', 'Dia'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/b/bb/Orpheus_Render.png/revision/latest?cb=20230302222401' },
  { nombre: 'Izanagi', arcana: 'Fool', nivel: 8,
    stats: { fuerza: 7, magia: 7, resistencia: 6, agilidad: 9, suerte: 6 },
    habilidades: ['Zio', 'Cleave'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/e/ec/IzanagiP4Full.png/revision/latest?cb=20230818092237' },
  { nombre: 'Arsène', arcana: 'Fool', nivel: 6,
    stats: { fuerza: 6, magia: 6, resistencia: 4, agilidad: 9, suerte: 4 },
    habilidades: ['Eiha', 'Cleave'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/1/19/Arsene.png/revision/latest?cb=20170612163748' },
  { nombre: 'Pixie', arcana: 'Lovers', nivel: 2,
    stats: { fuerza: 1, magia: 7, resistencia: 3, agilidad: 5, suerte: 4 },
    habilidades: ['Dia', 'Zio'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/3/30/MT2_Pixie.png/revision/latest?cb=20231120092123' },
  { nombre: 'Jack Frost', arcana: 'Magician', nivel: 5,
    stats: { fuerza: 3, magia: 9, resistencia: 3, agilidad: 5, suerte: 8 },
    habilidades: ['Bufu', 'Mabufu'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/e/e6/00072_Jack_Frost.png/revision/latest?cb=20220727075637' },
  { nombre: 'Angel', arcana: 'Priestess', nivel: 4,
    stats: { fuerza: 3, magia: 8, resistencia: 5, agilidad: 5, suerte: 5 },
    habilidades: ['Dia', 'Media'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/f/f2/00029_Angel_%28Reupload%29.png/revision/latest?cb=20220525024440' },
  { nombre: 'Titania', arcana: 'Empress', nivel: 15,
    stats: { fuerza: 7, magia: 14, resistencia: 11, agilidad: 9, suerte: 11 },
    habilidades: ['Media', 'Garula'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/f/fb/00303_Titania.png/revision/latest?cb=20221116132051' },
  { nombre: 'Cerberus', arcana: 'Chariot', nivel: 10,
    stats: { fuerza: 12, magia: 3, resistencia: 9, agilidad: 11, suerte: 5 },
    habilidades: ['Agi', 'Rampage'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/1/1b/Cerberus_%28MT_Art%29.png/revision/latest?cb=20210802021711' },
  { nombre: 'Mothman', arcana: 'Hermit', nivel: 18,
    stats: { fuerza: 10, magia: 14, resistencia: 10, agilidad: 16, suerte: 8 },
    habilidades: ['Bufula', 'Dodge'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/e/e0/Mothmanof.png/revision/latest?cb=20210912210516' },
  { nombre: 'Yoshitsune', arcana: 'Star', nivel: 42,
    stats: { fuerza: 28, magia: 14, resistencia: 19, agilidad: 33, suerte: 21 },
    habilidades: ['Hassou Tobi', 'Brave Blade'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/b/bf/Yoshitsune_DevSum.png/revision/latest?cb=20231202235420' },
  { nombre: 'Thor', arcana: 'Emperor', nivel: 25,
    stats: { fuerza: 19, magia: 19, resistencia: 15, agilidad: 13, suerte: 10 },
    habilidades: ['Ziodyne', 'Thunder Reign'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/2/22/00007_Thor_%28Reupload%29.png/revision/latest?cb=20220525024430' },
  { nombre: 'Satan', arcana: 'Judgement', nivel: 90,
    stats: { fuerza: 54, magia: 54, resistencia: 51, agilidad: 36, suerte: 36 },
    habilidades: ['Megidolaon', 'Judgement Light'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/f/fb/Satan_MT_II.png/revision/latest?cb=20231124025321' },

  // --- Segunda tanda: más Personas repartidas por los 22 arcanos ---
  { nombre: 'Forneus', arcana: 'Magician', nivel: 12,
    stats: { fuerza: 4, magia: 16, resistencia: 6, agilidad: 10, suerte: 8 },
    habilidades: ['Bufu', 'Mind Charge'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/4/4a/00086_Forneus.png/revision/latest?cb=20220731054145' },
  { nombre: 'Ara Mitama', arcana: 'Priestess', nivel: 7,
    stats: { fuerza: 2, magia: 12, resistencia: 4, agilidad: 5, suerte: 9 },
    habilidades: ['Dia', 'Enduring Soul'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/f/f7/Ara_Mitama_%28Devil_Summoner_Art%29.png/revision/latest?cb=20240416031913' },
  { nombre: 'Kikuri-Hime', arcana: 'Empress', nivel: 20,
    stats: { fuerza: 8, magia: 19, resistencia: 13, agilidad: 8, suerte: 15 },
    habilidades: ['Mediarama', 'Samarecarm'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/3/33/00009_Kikuri-hime_%28Reupload%29.png/revision/latest?cb=20220525024457' },
  { nombre: 'Odin', arcana: 'Emperor', nivel: 35,
    stats: { fuerza: 25, magia: 22, resistencia: 20, agilidad: 17, suerte: 15 },
    habilidades: ['Thunder Reign', 'Ziodyne'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/f/f5/Odin_%28MTII_Art%29.png/revision/latest?cb=20240627095126' },
  { nombre: 'Ganesha', arcana: 'Hierophant', nivel: 22,
    stats: { fuerza: 14, magia: 19, resistencia: 16, agilidad: 7, suerte: 12 },
    habilidades: ['Garudyne', 'Mind Charge'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/d/d5/00052_Ganesha.png/revision/latest?cb=20220722052205' },
  { nombre: 'Anubis', arcana: 'Hierophant', nivel: 24,
    stats: { fuerza: 21, magia: 12, resistencia: 16, agilidad: 14, suerte: 9 },
    habilidades: ['Diarahan', 'Vorpal Blade'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/d/d3/SMT_II_Anubis.png/revision/latest?cb=20240502075350' },
  { nombre: 'Andras', arcana: 'Lovers', nivel: 14,
    stats: { fuerza: 12, magia: 7, resistencia: 9, agilidad: 14, suerte: 7 },
    habilidades: ['Brutal Slash', 'Fear Boost'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/a/a2/00089_Andras.png/revision/latest?cb=20220731054149' },
  { nombre: 'Take-Minakata', arcana: 'Chariot', nivel: 27,
    stats: { fuerza: 24, magia: 7, resistencia: 18, agilidad: 20, suerte: 11 },
    habilidades: ['Assault Dive', 'Rampage'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/e/e5/00460_Takeminakata.png/revision/latest?cb=20220827150731' },
  { nombre: 'Ose', arcana: 'Justice', nivel: 16,
    stats: { fuerza: 12, magia: 12, resistencia: 10, agilidad: 10, suerte: 8 },
    habilidades: ['Confuse Boost', 'Panic Voice'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/2/28/Ose_%28Dx2_Art%29.png/revision/latest?cb=20210705093954' },
  { nombre: 'Vishnu', arcana: 'Justice', nivel: 55,
    stats: { fuerza: 35, magia: 37, resistencia: 29, agilidad: 23, suerte: 23 },
    habilidades: ['Divine Judgement', 'Salvation'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/f/f3/Vishnu_%28MTII_Art%29.png/revision/latest?cb=20240617092254' },
  { nombre: 'Berith', arcana: 'Hermit', nivel: 13,
    stats: { fuerza: 12, magia: 10, resistencia: 8, agilidad: 10, suerte: 6 },
    habilidades: ['Agilao', 'Tarukaja'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/b/ba/00085_Berith.png/revision/latest?cb=20220731054145' },
  { nombre: 'Norn', arcana: 'Fortune', nivel: 30,
    stats: { fuerza: 12, magia: 24, resistencia: 15, agilidad: 15, suerte: 22 },
    habilidades: ['Luck Boost', 'Debilitate'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/e/e4/Norn_%28Dx2_Art%29.png/revision/latest?cb=20220302084901' },
  { nombre: 'Fortuna', arcana: 'Fortune', nivel: 18,
    stats: { fuerza: 6, magia: 14, resistencia: 8, agilidad: 12, suerte: 19 },
    habilidades: ["Lucky Sweep", "Fortune's Favor"],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/1/17/SH_Fortuna.png/revision/latest?cb=20240525135047' },
  { nombre: 'Rangda', arcana: 'Strength', nivel: 45,
    stats: { fuerza: 32, magia: 32, resistencia: 23, agilidad: 21, suerte: 14 },
    habilidades: ['Megidola', 'Curse Boost'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/f/f3/RangdaSMT2.jpg/revision/latest?cb=20080807180310' },
  { nombre: 'Thoth', arcana: 'Strength', nivel: 33,
    stats: { fuerza: 17, magia: 30, resistencia: 17, agilidad: 15, suerte: 15 },
    habilidades: ['Wisdom Wave', 'Mabufula'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/a/a1/NINE_Thoth.png/revision/latest?cb=20240620111954' },
  { nombre: 'Mokoi', arcana: 'HangedMan', nivel: 9,
    stats: { fuerza: 7, magia: 8, resistencia: 5, agilidad: 10, suerte: 7 },
    habilidades: ['Poison Breath', 'Sukukaja'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/0/08/Mokoi.png/revision/latest?cb=20240416030710' },
  { nombre: 'Alice', arcana: 'Death', nivel: 40,
    stats: { fuerza: 8, magia: 40, resistencia: 13, agilidad: 19, suerte: 32 },
    habilidades: ['Die For Me!', 'Mamudoon'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/f/f7/Smtalice.png/revision/latest?cb=20220227155358' },
  { nombre: 'Matador', arcana: 'Death', nivel: 20,
    stats: { fuerza: 15, magia: 10, resistencia: 11, agilidad: 17, suerte: 10 },
    habilidades: ['Brave Blade', 'Charge'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/0/04/Matador_%28SMT_Art%29.png/revision/latest?cb=20210912215030' },
  { nombre: 'Yatagarasu', arcana: 'Temperance', nivel: 17,
    stats: { fuerza: 12, magia: 12, resistencia: 10, agilidad: 14, suerte: 10 },
    habilidades: ['Garula', 'Trafuri'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/0/0b/00037_Yatagarasu.png/revision/latest?cb=20220720103451' },
  { nombre: 'Ame-no-Uzume', arcana: 'Temperance', nivel: 15,
    stats: { fuerza: 7, magia: 13, resistencia: 7, agilidad: 11, suerte: 13 },
    habilidades: ['Dance of Delusion', 'Charm Boost'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/5/57/00010_Ame-no-Uzume_%28Reupload%29.png/revision/latest?cb=20220525024430' },
  { nombre: 'Astaroth', arcana: 'Devil', nivel: 38,
    stats: { fuerza: 28, magia: 28, resistencia: 23, agilidad: 13, suerte: 13 },
    habilidades: ['Megido', 'Poison Breath'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/0/0a/Astaroth_%28MTII_Art%29.png/revision/latest?cb=20231123060845' },
  { nombre: 'Belial', arcana: 'Devil', nivel: 42,
    stats: { fuerza: 32, magia: 32, resistencia: 24, agilidad: 16, suerte: 13 },
    habilidades: ['Maeigaon', 'Curse Breath'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/3/3a/Belial_MTII.png/revision/latest?cb=20231201065732' },
  { nombre: 'Setanta', arcana: 'Tower', nivel: 19,
    stats: { fuerza: 17, magia: 6, resistencia: 11, agilidad: 19, suerte: 8 },
    habilidades: ['Brutal Slash', 'Rakukaja'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/4/4c/Setanta_%28Dx2%29.png/revision/latest?cb=20230622071653' },
  { nombre: 'Nebiros', arcana: 'Tower', nivel: 26,
    stats: { fuerza: 21, magia: 19, resistencia: 16, agilidad: 12, suerte: 9 },
    habilidades: ['Curse Boost', 'Mudoon'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/2/28/00080_Nebiros.png/revision/latest?cb=20220731054145' },
  { nombre: 'Cu Chulainn', arcana: 'Star', nivel: 31,
    stats: { fuerza: 24, magia: 11, resistencia: 16, agilidad: 24, suerte: 13 },
    habilidades: ['Vorpal Blade', 'Brave Blade'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/1/1a/00066_Cu_Chulainn.png/revision/latest?cb=20220727075630' },
  { nombre: 'Queen Mab', arcana: 'Moon', nivel: 23,
    stats: { fuerza: 11, magia: 22, resistencia: 11, agilidad: 13, suerte: 13 },
    habilidades: ['Mabufula', 'Marin Karin'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/c/cb/Queen_Medb.png/revision/latest?cb=20240515042730' },
  { nombre: 'Black Frost', arcana: 'Moon', nivel: 28,
    stats: { fuerza: 13, magia: 23, resistencia: 11, agilidad: 17, suerte: 17 },
    habilidades: ['Mabufula', 'Ice Amp'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/d/da/00499_Black_Frost.png/revision/latest?cb=20220822115856' },
  { nombre: 'Amaterasu', arcana: 'Sun', nivel: 50,
    stats: { fuerza: 26, magia: 37, resistencia: 29, agilidad: 19, suerte: 24 },
    habilidades: ['Judgement Light', 'Salvation'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/8/8b/Amateratsu.jpg/revision/latest?cb=20080806033633' },
  { nombre: 'Michael', arcana: 'Judgement', nivel: 60,
    stats: { fuerza: 37, magia: 40, resistencia: 34, agilidad: 26, suerte: 23 },
    habilidades: ['Megidolaon', 'Divine Shot'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/c/ce/00021_Michael.png/revision/latest?cb=20220530041014' },
  { nombre: 'Lucifer', arcana: 'World', nivel: 99,
    stats: { fuerza: 58, magia: 58, resistencia: 52, agilidad: 45, suerte: 39 },
    habilidades: ['Morning Star', 'Grace of Ruin'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/d/dd/Lucifer_MTII.png/revision/latest?cb=20231201055634' },

// --- Fool ---
  { nombre: 'Erebus', arcana: 'Fool', nivel: 95,
    stats: { fuerza: 33, magia: 55, resistencia: 55, agilidad: 61, suerte: 39 },
    habilidades: ['Wind Boost', 'Tarukaja'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/3/34/Erebus.png/revision/latest?cb=20120707063207' },
  { nombre: 'Nyx Avatar', arcana: 'Fool', nivel: 90,
    stats: { fuerza: 27, magia: 41, resistencia: 88, agilidad: 28, suerte: 46 },
    habilidades: ['Ice Boost', 'Fire Boost'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/5/52/Nyx_-_P3_Art.png/revision/latest?cb=20220907213808' },
  { nombre: 'Loki', arcana: 'Fool', nivel: 38,
    stats: { fuerza: 19, magia: 11, resistencia: 27, agilidad: 16, suerte: 34 },
    habilidades: ['Mediarama', 'Agidyne'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/9/94/Loki-novel.jpg/revision/latest?cb=20090625204551' },
  { nombre: 'Magatsu-Izanagi', arcana: 'Fool', nivel: 92,
    stats: { fuerza: 47, magia: 49, resistencia: 41, agilidad: 36, suerte: 63 },
    habilidades: ['Diarama', 'Megidola'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/9/98/P4-MagatsuIzanagi.jpg/revision/latest?cb=20090124003256' },
  { nombre: 'Pallas Athena', arcana: 'Fool', nivel: 70,
    stats: { fuerza: 15, magia: 35, resistencia: 42, agilidad: 54, suerte: 37 },
    habilidades: ['Sonic Punch', 'Agidyne'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/6/6e/Pallas_Athena_DS.jpg/revision/latest?cb=20230305110205' },
  { nombre: 'Legion', arcana: 'Fool', nivel: 18,
    stats: { fuerza: 9, magia: 6, resistencia: 7, agilidad: 21, suerte: 14 },
    habilidades: ['Agilao', 'Tarukaja'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/d/de/LegionSMT.jpg/revision/latest?cb=20080709034919' },

  // --- Magician ---
  { nombre: 'Hermes', arcana: 'Magician', nivel: 25,
    stats: { fuerza: 12, magia: 10, resistencia: 17, agilidad: 18, suerte: 17 },
    habilidades: ['Marin Karin', 'Brave Blade'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/d/df/HermesP2.png/revision/latest?cb=20131125094533' },
  { nombre: 'Mercurius', arcana: 'Magician', nivel: 27,
    stats: { fuerza: 18, magia: 14, resistencia: 8, agilidad: 15, suerte: 25 },
    habilidades: ['Bufu', 'Garu'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/7/78/298_-_Mercurius.jpg/revision/latest?cb=20120315042056' },
  { nombre: 'Jiraiya', arcana: 'Magician', nivel: 30,
    stats: { fuerza: 7, magia: 18, resistencia: 18, agilidad: 23, suerte: 22 },
    habilidades: ['Rampage', 'Bufudyne'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/3/31/SMT2Jiraiya.jpg/revision/latest?cb=20210917023402' },
  { nombre: 'Nekomata', arcana: 'Magician', nivel: 10,
    stats: { fuerza: 10, magia: 7, resistencia: 4, agilidad: 10, suerte: 7 },
    habilidades: ['Megido', 'Assault Dive'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/a/a8/Nekomata_%28MT_Art%29.png/revision/latest?cb=20210802021712' },
  { nombre: 'Jack-o\'-Lantern', arcana: 'Magician', nivel: 8,
    stats: { fuerza: 9, magia: 7, resistencia: 8, agilidad: 5, suerte: 6 },
    habilidades: ['Mediarama', 'Garula'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/1/1f/Jack_O%27Lantern_%28MTII_Art%29.png/revision/latest?cb=20231202064840' },

  // --- Priestess ---
  { nombre: 'Izanami', arcana: 'Priestess', nivel: 90,
    stats: { fuerza: 35, magia: 28, resistencia: 47, agilidad: 83, suerte: 38 },
    habilidades: ['Ice Boost', 'Megidola'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/5/55/DDS-MegamiTensei_109.jpg/revision/latest?cb=20170121111657' },
  { nombre: 'Skadi', arcana: 'Priestess', nivel: 45,
    stats: { fuerza: 29, magia: 23, resistencia: 23, agilidad: 32, suerte: 15 },
    habilidades: ['Agilao', 'Rampage'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/f/fa/SMT_III_Skadi.png/revision/latest?cb=20240924102919' },
  { nombre: 'Sarasvati', arcana: 'Priestess', nivel: 30,
    stats: { fuerza: 24, magia: 12, resistencia: 19, agilidad: 9, suerte: 24 },
    habilidades: ['Ice Boost', 'Sonic Punch'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/6/6b/SMT_II_Sarasvat%C4%AB.png/revision/latest?cb=20240502081700' },
  { nombre: 'Silky', arcana: 'Priestess', nivel: 8,
    stats: { fuerza: 6, magia: 4, resistencia: 6, agilidad: 8, suerte: 10 },
    habilidades: ['Megidola', 'Sonic Punch'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/c/c3/Silky_%28Dx2_Art%29.png/revision/latest?cb=20210708051036' },
  { nombre: 'Scathach', arcana: 'Priestess', nivel: 42,
    stats: { fuerza: 23, magia: 16, resistencia: 26, agilidad: 34, suerte: 18 },
    habilidades: ['Endure', 'Charge'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/9/92/00612_Scathach.png/revision/latest?cb=20220902033035' },
  { nombre: 'Konohana Sakuya', arcana: 'Priestess', nivel: 28,
    stats: { fuerza: 20, magia: 15, resistencia: 23, agilidad: 15, suerte: 9 },
    habilidades: ['Brave Blade', 'Debilitate'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/d/d9/Konohana_Sakuya_art.png/revision/latest?cb=20231218222236' },
  { nombre: 'Lakshmi', arcana: 'Priestess', nivel: 50,
    stats: { fuerza: 18, magia: 39, resistencia: 42, agilidad: 17, suerte: 19 },
    habilidades: ['Tarukaja', 'Debilitate'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/e/e4/00008_Lakshmi_%28Reupload%29.png/revision/latest?cb=20220525024430' },

  // --- Empress ---
  { nombre: 'Ishtar', arcana: 'Empress', nivel: 55,
    stats: { fuerza: 30, magia: 35, resistencia: 23, agilidad: 42, suerte: 18 },
    habilidades: ['Endure', 'Garudyne'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/2/2c/SMT_II_Ishtar.png/revision/latest?cb=20240531050528' },
  { nombre: 'Isis', arcana: 'Empress', nivel: 50,
    stats: { fuerza: 19, magia: 33, resistencia: 24, agilidad: 21, suerte: 38 },
    habilidades: ['Curse Boost', 'Media'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/2/2f/Isis_SMT_Nine.png/revision/latest?cb=20240411080644' },
  { nombre: 'Durga', arcana: 'Empress', nivel: 48,
    stats: { fuerza: 36, magia: 32, resistencia: 34, agilidad: 11, suerte: 17 },
    habilidades: ['Dekaja', 'Sukukaja'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/e/eb/SMT_II_Durga.png/revision/latest?cb=20240502080018' },
  { nombre: 'Gaia', arcana: 'Empress', nivel: 65,
    stats: { fuerza: 20, magia: 64, resistencia: 43, agilidad: 22, suerte: 22 },
    habilidades: ['Hamaon', 'Agidyne'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/a/af/Gaia_MT.png/revision/latest?cb=20200314003309' },
  { nombre: 'Kali', arcana: 'Empress', nivel: 52,
    stats: { fuerza: 19, magia: 28, resistencia: 26, agilidad: 38, suerte: 29 },
    habilidades: ['Ziodyne', 'Zio'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/a/a1/Kali_%28MTII_Art%29.png/revision/latest?cb=20210811142349' },
  { nombre: 'Mother Harlot', arcana: 'Empress', nivel: 70,
    stats: { fuerza: 37, magia: 32, resistencia: 26, agilidad: 46, suerte: 42 },
    habilidades: ['Garudyne', 'Bufu'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/d/df/Mother_Harlot_%28SMTIII_Art%29.png/revision/latest?cb=20210912205643' },
  { nombre: 'Astarte', arcana: 'Empress', nivel: 38,
    stats: { fuerza: 12, magia: 14, resistencia: 22, agilidad: 27, suerte: 31 },
    habilidades: ['Bufu', 'Agi'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/b/b4/Astarte_Trinity_Soul.jpg/revision/latest?cb=20120821014040' },

  // --- Emperor ---
  { nombre: 'Asura', arcana: 'Emperor', nivel: 55,
    stats: { fuerza: 37, magia: 49, resistencia: 26, agilidad: 16, suerte: 18 },
    habilidades: ['Endure', 'Debilitate'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/6/6f/Asura_%28MTII_Art%29.png/revision/latest?cb=20210802130759' },
  { nombre: 'Susano-o', arcana: 'Emperor', nivel: 40,
    stats: { fuerza: 14, magia: 14, resistencia: 27, agilidad: 26, suerte: 31 },
    habilidades: ['Mediarama', 'Dekaja'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/1/1b/00232_Susanoo.png/revision/latest?cb=20230317090704' },
  { nombre: 'Baal', arcana: 'Emperor', nivel: 50,
    stats: { fuerza: 16, magia: 33, resistencia: 21, agilidad: 44, suerte: 21 },
    habilidades: ['Hama', 'Ice Boost'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/c/cd/SMT_II_Baal.png/revision/latest?cb=20240627095207' },
  { nombre: 'Zeus', arcana: 'Emperor', nivel: 65,
    stats: { fuerza: 39, magia: 35, resistencia: 51, agilidad: 16, suerte: 30 },
    habilidades: ['Zionga', 'Agilao'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/c/c1/Zeus_KMT.png/revision/latest?cb=20230530052954' },
  { nombre: 'Indra', arcana: 'Emperor', nivel: 48,
    stats: { fuerza: 15, magia: 14, resistencia: 45, agilidad: 32, suerte: 24 },
    habilidades: ['Poison Breath', 'Wind Boost'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/8/81/00002_Indra.png/revision/latest?cb=20220525023638' },
  { nombre: 'Marduk', arcana: 'Emperor', nivel: 52,
    stats: { fuerza: 16, magia: 16, resistencia: 31, agilidad: 43, suerte: 34 },
    habilidades: ['Mudo', 'Regenerate 1'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/4/4b/Marduk.jpg/revision/latest?cb=20100615154004' },
  { nombre: 'King Frost', arcana: 'Emperor', nivel: 20,
    stats: { fuerza: 13, magia: 8, resistencia: 19, agilidad: 14, suerte: 9 },
    habilidades: ['Garula', 'Garudyne'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/5/58/SMT_II_King_Frost.png/revision/latest?cb=20240405105049' },

  // --- Hierophant ---
  { nombre: 'Beelzebub', arcana: 'Hierophant', nivel: 75,
    stats: { fuerza: 21, magia: 53, resistencia: 23, agilidad: 57, suerte: 42 },
    habilidades: ['Zionga', 'Tarukaja'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/b/b2/MTII_Beelzebub.png/revision/latest?cb=20231120004820' },
  { nombre: 'Kohryu', arcana: 'Hierophant', nivel: 55,
    stats: { fuerza: 14, magia: 52, resistencia: 16, agilidad: 19, suerte: 45 },
    habilidades: ['Hama', 'Charge'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/a/a3/Kohryu_%28Dx2_Art%29.png/revision/latest?cb=20210703223834' },
  { nombre: 'Daisoujou', arcana: 'Hierophant', nivel: 60,
    stats: { fuerza: 30, magia: 24, resistencia: 36, agilidad: 27, suerte: 42 },
    habilidades: ['Sonic Punch', 'Regenerate 1'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/1/1f/00193_Dais%C5%8Dj%C5%8D.png/revision/latest?cb=20230209033704' },
  { nombre: 'Hachiman', arcana: 'Hierophant', nivel: 42,
    stats: { fuerza: 28, magia: 22, resistencia: 23, agilidad: 31, suerte: 12 },
    habilidades: ['Tarukaja', 'Zionga'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/d/db/Hachiman_%28Dx2_Art%29.png/revision/latest?cb=20221201122038' },
  { nombre: 'Dantalion', arcana: 'Hierophant', nivel: 25,
    stats: { fuerza: 16, magia: 13, resistencia: 14, agilidad: 12, suerte: 20 },
    habilidades: ['Zio', 'Endure'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/0/07/Dantalian.png/revision/latest?cb=20090630204356' },
  { nombre: 'Bishamonten (demon)', arcana: 'Hierophant', nivel: 45,
    stats: { fuerza: 22, magia: 18, resistencia: 47, agilidad: 14, suerte: 21 },
    habilidades: ['Cleave', 'Poison Breath'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/6/6f/Bishamonten.jpg/revision/latest?cb=20100527052026' },
  { nombre: 'Feng Huang', arcana: 'Hierophant', nivel: 30,
    stats: { fuerza: 19, magia: 23, resistencia: 8, agilidad: 23, suerte: 15 },
    habilidades: ['Elec Boost', 'Ziodyne'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/3/30/00039_Feng_Huang.png/revision/latest?cb=20220720103505' },

  // --- Lovers ---
  { nombre: 'Eros', arcana: 'Lovers', nivel: 25,
    stats: { fuerza: 10, magia: 10, resistencia: 14, agilidad: 21, suerte: 20 },
    habilidades: ['Endure', 'Bufudyne'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/6/64/Eros_P2.png/revision/latest?cb=20131125112243' },
  { nombre: 'Hecate', arcana: 'Lovers', nivel: 40,
    stats: { fuerza: 30, magia: 17, resistencia: 8, agilidad: 29, suerte: 26 },
    habilidades: ['Rampage', 'Megidola'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/a/ab/Hecate_%28MT_Art%29.png/revision/latest?cb=20210802021711' },
  { nombre: 'Carmen', arcana: 'Lovers', nivel: 22,
    stats: { fuerza: 11, magia: 5, resistencia: 18, agilidad: 15, suerte: 18 },
    habilidades: ['Debilitate', 'Mudoon'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/a/a6/S06_chara69jsyf.png/revision/latest?cb=20170713152516' },
  { nombre: 'Undine', arcana: 'Lovers', nivel: 12,
    stats: { fuerza: 8, magia: 9, resistencia: 5, agilidad: 10, suerte: 12 },
    habilidades: ['Agidyne', 'Garula'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/f/fd/00044_Undine.png/revision/latest?cb=20220720103509' },
  { nombre: 'Kanzeon', arcana: 'Lovers', nivel: 45,
    stats: { fuerza: 29, magia: 16, resistencia: 38, agilidad: 21, suerte: 20 },
    habilidades: ['Agi', 'Brave Blade'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/e/e5/Kanzeon.png/revision/latest?cb=20141209123251' },

  // --- Chariot ---
  { nombre: 'Palladion', arcana: 'Chariot', nivel: 25,
    stats: { fuerza: 17, magia: 15, resistencia: 17, agilidad: 7, suerte: 18 },
    habilidades: ['Debilitate', 'Garula'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/4/42/Palladion.png/revision/latest?cb=20241122032316' },
  { nombre: 'Ares', arcana: 'Chariot', nivel: 40,
    stats: { fuerza: 13, magia: 11, resistencia: 26, agilidad: 27, suerte: 34 },
    habilidades: ['Regenerate 1', 'Mudoon'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/3/35/SMT_II_Ares.png/revision/latest?cb=20240502075352' },
  { nombre: 'Chimera', arcana: 'Chariot', nivel: 18,
    stats: { fuerza: 13, magia: 12, resistencia: 14, agilidad: 8, suerte: 10 },
    habilidades: ['Rampage', 'Mudoon'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/a/a9/00033_Chimera.png/revision/latest?cb=20220608055516' },
  { nombre: 'Minotaur', arcana: 'Chariot', nivel: 20,
    stats: { fuerza: 10, magia: 12, resistencia: 15, agilidad: 11, suerte: 15 },
    habilidades: ['Ziodyne', 'Mind Charge'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/b/be/Minotaur_%28MT_Art%29.png/revision/latest?cb=20210802021712' },
  { nombre: 'Oni', arcana: 'Chariot', nivel: 15,
    stats: { fuerza: 7, magia: 5, resistencia: 22, agilidad: 8, suerte: 9 },
    habilidades: ['Poison Breath', 'Curse Boost'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/c/c4/SMT_III_Oni_Compressed.png/revision/latest?cb=20240328100803' },
  { nombre: 'Talos', arcana: 'Chariot', nivel: 35,
    stats: { fuerza: 10, magia: 20, resistencia: 18, agilidad: 34, suerte: 16 },
    habilidades: ['Megido', 'Agi'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/c/c9/Talos.JPG/revision/latest?cb=20100529171651' },
  { nombre: 'Shiva', arcana: 'Chariot', nivel: 70,
    stats: { fuerza: 38, magia: 18, resistencia: 41, agilidad: 60, suerte: 26 },
    habilidades: ['Debilitate', 'Wind Boost'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/7/7c/Shiva_MTII.png/revision/latest?cb=20231122105315' },

  // --- Justice ---
  { nombre: 'Metatron', arcana: 'Justice', nivel: 80,
    stats: { fuerza: 20, magia: 56, resistencia: 56, agilidad: 50, suerte: 25 },
    habilidades: ['Dia', 'Agi'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/8/88/SMT_II_Metatron.png/revision/latest?cb=20240502080535' },
  { nombre: 'Archangel', arcana: 'Justice', nivel: 20,
    stats: { fuerza: 14, magia: 14, resistencia: 6, agilidad: 8, suerte: 21 },
    habilidades: ['Charge', 'Rampage'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/3/31/00028_Archangel.png/revision/latest?cb=20220608055503' },
  { nombre: 'Dominion', arcana: 'Justice', nivel: 30,
    stats: { fuerza: 28, magia: 10, resistencia: 19, agilidad: 23, suerte: 8 },
    habilidades: ['Sonic Punch', 'Hamaon'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/7/7d/00027_Dominion.png/revision/latest?cb=20220604013811' },
  { nombre: 'Robin Hood', arcana: 'Justice', nivel: 15,
    stats: { fuerza: 9, magia: 12, resistencia: 7, agilidad: 12, suerte: 12 },
    habilidades: ['Mudo', 'Tarukaja'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/a/a8/Robin_Hood_P5R.png/revision/latest?cb=20190816143020' },
  { nombre: 'Jeanne d\'Arc', arcana: 'Justice', nivel: 48,
    stats: { fuerza: 28, magia: 16, resistencia: 16, agilidad: 28, suerte: 43 },
    habilidades: ['Assault Dive', 'Mudoon'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/e/e4/00975_Jeanne_d%27Arc.png/revision/latest?cb=20240208054436' },
  { nombre: 'Helios', arcana: 'Justice', nivel: 50,
    stats: { fuerza: 32, magia: 24, resistencia: 26, agilidad: 26, suerte: 28 },
    habilidades: ['Tarukaja', 'Cleave'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/5/5a/Helios_%28P2EP_Art%29.png/revision/latest?cb=20210912231416' },
  { nombre: 'Uriel', arcana: 'Justice', nivel: 55,
    stats: { fuerza: 11, magia: 37, resistencia: 37, agilidad: 42, suerte: 19 },
    habilidades: ['Elec Boost', 'Debilitate'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/e/e5/Uriel_%28MTII_Art%29.png/revision/latest?cb=20210802032735' },

  // --- Hermit ---
  { nombre: 'Byakko', arcana: 'Hermit', nivel: 45,
    stats: { fuerza: 21, magia: 13, resistencia: 29, agilidad: 18, suerte: 43 },
    habilidades: ['Zionga', 'Bufu'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/4/40/ByakkoSMT2.jpg/revision/latest?cb=20080808014542' },
  { nombre: 'Genbu', arcana: 'Hermit', nivel: 45,
    stats: { fuerza: 30, magia: 17, resistencia: 26, agilidad: 28, suerte: 22 },
    habilidades: ['Agidyne', 'Sukukaja'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/5/5f/00040_Genbu.png/revision/latest?cb=20220720103504' },
  { nombre: 'Fafnir', arcana: 'Hermit', nivel: 40,
    stats: { fuerza: 13, magia: 22, resistencia: 19, agilidad: 25, suerte: 32 },
    habilidades: ['Diarama', 'Bufu'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/0/0f/00136_F%C3%A1fnir.png/revision/latest?cb=20220929114046' },
  { nombre: 'Koropokkuru', arcana: 'Hermit', nivel: 6,
    stats: { fuerza: 8, magia: 6, resistencia: 3, agilidad: 5, suerte: 7 },
    habilidades: ['Ice Boost', 'Mudoon'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/6/61/SH_Koropokkur.png/revision/latest?cb=20240416030233' },
  { nombre: 'Prometheus', arcana: 'Hermit', nivel: 50,
    stats: { fuerza: 23, magia: 31, resistencia: 24, agilidad: 29, suerte: 28 },
    habilidades: ['Dekaja', 'Rampage'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/1/1c/DS_Prometheus.png/revision/latest?cb=20240504050555' },
  { nombre: 'Naga', arcana: 'Hermit', nivel: 16,
    stats: { fuerza: 13, magia: 11, resistencia: 4, agilidad: 11, suerte: 14 },
    habilidades: ['Vorpal Blade', 'Agilao'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/3/35/Naga.png/revision/latest?cb=20190329184245' },
  { nombre: 'Nue', arcana: 'Hermit', nivel: 22,
    stats: { fuerza: 12, magia: 17, resistencia: 17, agilidad: 6, suerte: 16 },
    habilidades: ['Agidyne', 'Debilitate'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/4/4b/159_Nue.jpg/revision/latest?cb=20110831125528' },

  // --- Fortune ---
  { nombre: 'Skuld', arcana: 'Fortune', nivel: 28,
    stats: { fuerza: 23, magia: 11, resistencia: 12, agilidad: 21, suerte: 15 },
    habilidades: ['Media', 'Elec Boost'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/b/b5/Skuld_%28Persona_Art%29.png/revision/latest?cb=20241205043557' },
  { nombre: 'Chronos', arcana: 'Fortune', nivel: 65,
    stats: { fuerza: 13, magia: 53, resistencia: 48, agilidad: 32, suerte: 25 },
    habilidades: ['Mudo', 'Brave Blade'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/a/ab/ChronosP2.png/revision/latest?cb=20240412120835' },
  { nombre: 'Fenrir', arcana: 'Fortune', nivel: 48,
    stats: { fuerza: 29, magia: 24, resistencia: 26, agilidad: 27, suerte: 23 },
    habilidades: ['Sonic Punch', 'Regenerate 1'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/3/31/FenrirSMT.jpg/revision/latest?cb=20080803203251' },
  { nombre: 'Ariadne', arcana: 'Fortune', nivel: 18,
    stats: { fuerza: 6, magia: 11, resistencia: 15, agilidad: 14, suerte: 12 },
    habilidades: ['Zio', 'Elec Boost'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/b/b3/Ariadne_%28P4A%29.png/revision/latest?cb=20260629233424' },
  { nombre: 'Labrys', arcana: 'Fortune', nivel: 30,
    stats: { fuerza: 13, magia: 19, resistencia: 23, agilidad: 23, suerte: 8 },
    habilidades: ['Fire Boost', 'Mediarama'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/0/01/Labrysp4a.png/revision/latest?cb=20140521135010' },
  { nombre: 'Sukuna-Hikona', arcana: 'Fortune', nivel: 14,
    stats: { fuerza: 7, magia: 21, resistencia: 7, agilidad: 8, suerte: 7 },
    habilidades: ['Zio', 'Poison Breath'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/6/60/SMT2-Sukunahikona.jpg/revision/latest?cb=20210917021543' },
  { nombre: 'Yamato-Takeru', arcana: 'Fortune', nivel: 38,
    stats: { fuerza: 25, magia: 23, resistencia: 16, agilidad: 17, suerte: 25 },
    habilidades: ['Agilao', 'Dekaja'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/2/2c/Yamato_Takeru_SMTIV.jpg/revision/latest?cb=20130906131730' },

  // --- Strength ---
  { nombre: 'Siegfried', arcana: 'Strength', nivel: 45,
    stats: { fuerza: 39, magia: 16, resistencia: 32, agilidad: 18, suerte: 18 },
    habilidades: ['Hamaon', 'Tarukaja'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/9/96/Siegfried_%28Dx2_Art%29.png/revision/latest?cb=20210622164114' },
  { nombre: 'Valkyrie', arcana: 'Strength', nivel: 25,
    stats: { fuerza: 13, magia: 19, resistencia: 8, agilidad: 17, suerte: 18 },
    habilidades: ['Mudoon', 'Sukukaja'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/8/8f/Valkyrie_%28Dx2_Art%29.png/revision/latest?cb=20220721090652' },
  { nombre: 'Titan', arcana: 'Strength', nivel: 55,
    stats: { fuerza: 17, magia: 29, resistencia: 26, agilidad: 57, suerte: 17 },
    habilidades: ['Agidyne', 'Marin Karin'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/2/20/300px-Titan.jpg/revision/latest?cb=20210907210021' },
  { nombre: 'Koromaru', arcana: 'Strength', nivel: 12,
    stats: { fuerza: 8, magia: 11, resistencia: 7, agilidad: 8, suerte: 10 },
    habilidades: ['Agilao', 'Debilitate'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/1/13/Koromaru.png/revision/latest?cb=20230205052912' },
  { nombre: 'Python', arcana: 'Strength', nivel: 15,
    stats: { fuerza: 17, magia: 7, resistencia: 7, agilidad: 13, suerte: 7 },
    habilidades: ['Charge', 'Megidola'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/c/c0/Python.jpg/revision/latest?cb=20190330155610' },
  { nombre: 'Vasuki', arcana: 'Strength', nivel: 25,
    stats: { fuerza: 15, magia: 17, resistencia: 12, agilidad: 20, suerte: 11 },
    habilidades: ['Sonic Punch', 'Megido'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/6/68/Vasuki_%28Dx2_Art%29.png/revision/latest?cb=20210819064723' },
  { nombre: 'Kiyohime', arcana: 'Strength', nivel: 20,
    stats: { fuerza: 17, magia: 12, resistencia: 8, agilidad: 11, suerte: 14 },
    habilidades: ['Megido', 'Mudoon'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/4/43/Kiyohime_K.GIF/revision/latest?cb=20120617190241' },

  // --- HangedMan ---
  { nombre: 'Azazel', arcana: 'HangedMan', nivel: 50,
    stats: { fuerza: 24, magia: 30, resistencia: 35, agilidad: 12, suerte: 34 },
    habilidades: ['Fire Boost', 'Debilitate'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/c/c6/Azazel_%28Dx2_Art%29.png/revision/latest?cb=20210621061950' },
  { nombre: 'Barbatos', arcana: 'HangedMan', nivel: 25,
    stats: { fuerza: 7, magia: 18, resistencia: 19, agilidad: 23, suerte: 9 },
    habilidades: ['Zionga', 'Poison Breath'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/5/5a/Barbatos.jpg/revision/latest?cb=20190330035247' },
  { nombre: 'Inugami', arcana: 'HangedMan', nivel: 10,
    stats: { fuerza: 9, magia: 9, resistencia: 7, agilidad: 6, suerte: 7 },
    habilidades: ['Charge', 'Bufu'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/0/02/Inugami_%28Dx2_Art%29.png/revision/latest?cb=20240516090123' },
  { nombre: 'Orthrus', arcana: 'HangedMan', nivel: 14,
    stats: { fuerza: 14, magia: 11, resistencia: 5, agilidad: 14, suerte: 4 },
    habilidades: ['Curse Boost', 'Agilao'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/d/d8/Orthrus_%28MTII_Art%29.png/revision/latest?cb=20210811142353' },
  { nombre: 'Odysseus', arcana: 'HangedMan', nivel: 30,
    stats: { fuerza: 12, magia: 29, resistencia: 22, agilidad: 12, suerte: 12 },
    habilidades: ['Mudoon', 'Charge'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/a/aa/Odysseus_%28P2EP_Art%29.png/revision/latest?cb=20210912231803' },
  { nombre: 'Moloch', arcana: 'HangedMan', nivel: 45,
    stats: { fuerza: 15, magia: 24, resistencia: 25, agilidad: 43, suerte: 16 },
    habilidades: ['Garula', 'Garudyne'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/b/ba/Moloch_MT_II.png/revision/latest?cb=20231123071122' },

  // --- Death ---
  { nombre: 'Hades', arcana: 'Death', nivel: 60,
    stats: { fuerza: 19, magia: 43, resistencia: 25, agilidad: 26, suerte: 46 },
    habilidades: ['Media', 'Brave Blade'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/8/81/Hades_%28Comp%29.png/revision/latest?cb=20231012023709' },
  { nombre: 'Chernobog', arcana: 'Death', nivel: 45,
    stats: { fuerza: 10, magia: 38, resistencia: 21, agilidad: 22, suerte: 33 },
    habilidades: ['Vorpal Blade', 'Zio'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/2/29/233_-_Chernobog.jpg/revision/latest?cb=20120419031935' },
  { nombre: 'Hel', arcana: 'Death', nivel: 50,
    stats: { fuerza: 24, magia: 31, resistencia: 17, agilidad: 32, suerte: 31 },
    habilidades: ['Agilao', 'Curse Boost'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/f/fd/Hel_%28Dx2_Art%29.png/revision/latest?cb=20230216085625' },
  { nombre: 'Charon', arcana: 'Death', nivel: 20,
    stats: { fuerza: 16, magia: 11, resistencia: 11, agilidad: 8, suerte: 16 },
    habilidades: ['Vorpal Blade', 'Megidola'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/e/ec/Charon_SMTDS_Novel.jpg/revision/latest?cb=20200503132849' },
  { nombre: 'Samael', arcana: 'Death', nivel: 55,
    stats: { fuerza: 49, magia: 27, resistencia: 27, agilidad: 14, suerte: 30 },
    habilidades: ['Megido', 'Regenerate 1'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/e/e0/00078_Samael_%28Reupload%29.png/revision/latest?cb=20220731064342' },
  { nombre: 'Nyx', arcana: 'Death', nivel: 99,
    stats: { fuerza: 67, magia: 44, resistencia: 56, agilidad: 45, suerte: 41 },
    habilidades: ['Diarama', 'Megidola'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/3/30/SMT_II_Nyx.png/revision/latest?cb=20240502081014' },
  { nombre: 'Rhadamanthus', arcana: 'Death', nivel: 35,
    stats: { fuerza: 11, magia: 25, resistencia: 20, agilidad: 20, suerte: 24 },
    habilidades: ['Curse Boost', 'Mudoon'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/6/67/Rhadamanthus_P2.png/revision/latest?cb=20131125113259' },

  // --- Temperance ---
  { nombre: 'Phoenix', arcana: 'Temperance', nivel: 22,
    stats: { fuerza: 19, magia: 8, resistencia: 7, agilidad: 14, suerte: 20 },
    habilidades: ['Fire Boost', 'Marin Karin'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/e/e3/PhoenixSMT.jpg/revision/latest?cb=20210917024527' },
  { nombre: 'Sylph', arcana: 'Temperance', nivel: 8,
    stats: { fuerza: 9, magia: 5, resistencia: 3, agilidad: 6, suerte: 11 },
    habilidades: ['Mudo', 'Endure'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/5/50/SMT_II_Sylph.png/revision/latest?cb=20240502081703' },
  { nombre: 'Suzaku', arcana: 'Temperance', nivel: 45,
    stats: { fuerza: 17, magia: 35, resistencia: 36, agilidad: 18, suerte: 17 },
    habilidades: ['Mudo', 'Garudyne'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/4/47/300px-Phoenix.jpg/revision/latest?cb=20210907185145' },
  { nombre: 'Harpy', arcana: 'Temperance', nivel: 10,
    stats: { fuerza: 6, magia: 8, resistencia: 9, agilidad: 10, suerte: 6 },
    habilidades: ['Agilao', 'Megidola'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/3/33/SMT_Harpy_Art_%28Censored%29.jpg/revision/latest?cb=20240529143301' },
  { nombre: 'Camazotz', arcana: 'Temperance', nivel: 25,
    stats: { fuerza: 13, magia: 18, resistencia: 14, agilidad: 15, suerte: 15 },
    habilidades: ['Debilitate', 'Regenerate 1'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/1/1e/Camazotz_%28Dx2_Art%29.png/revision/latest?cb=20210622160145' },
  { nombre: 'Seiryu', arcana: 'Temperance', nivel: 45,
    stats: { fuerza: 26, magia: 26, resistencia: 32, agilidad: 10, suerte: 28 },
    habilidades: ['Sonic Punch', 'Garudyne'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/9/99/Seiryu_%28SMTII_Artwork%29.png/revision/latest?cb=20210704110653' },
  { nombre: 'Mithra', arcana: 'Temperance', nivel: 35,
    stats: { fuerza: 10, magia: 23, resistencia: 23, agilidad: 18, suerte: 25 },
    habilidades: ['Diarama', 'Megidola'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/a/a6/Mitra_MTII.png/revision/latest?cb=20231201052935' },

  // --- Devil ---
  { nombre: 'Baphomet', arcana: 'Devil', nivel: 45,
    stats: { fuerza: 12, magia: 15, resistencia: 43, agilidad: 22, suerte: 31 },
    habilidades: ['Mudoon', 'Garudyne'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/e/e0/Baphomet_02.jpg/revision/latest?cb=20190402210306' },
  { nombre: 'Lilith', arcana: 'Devil', nivel: 50,
    stats: { fuerza: 36, magia: 33, resistencia: 17, agilidad: 17, suerte: 31 },
    habilidades: ['Megidola', 'Sukukaja'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/e/ea/00058_Lilith.png/revision/latest?cb=20220722052217' },
  { nombre: 'Succubus', arcana: 'Devil', nivel: 15,
    stats: { fuerza: 7, magia: 10, resistencia: 11, agilidad: 12, suerte: 11 },
    habilidades: ['Ziodyne', 'Brave Blade'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/d/de/MT201.jpg/revision/latest?cb=20111102194618' },
  { nombre: 'Pazuzu', arcana: 'Devil', nivel: 48,
    stats: { fuerza: 45, magia: 25, resistencia: 12, agilidad: 27, suerte: 21 },
    habilidades: ['Zio', 'Mediarama'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/a/ac/MTII_Pazuzu.png/revision/latest?cb=20231120015133' },
  { nombre: 'Basilisk', arcana: 'Devil', nivel: 18,
    stats: { fuerza: 16, magia: 14, resistencia: 4, agilidad: 10, suerte: 14 },
    habilidades: ['Brave Blade', 'Garula'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/4/4e/00138_Basilisk.png/revision/latest?cb=20220929114059' },
  { nombre: 'Lich', arcana: 'Devil', nivel: 28,
    stats: { fuerza: 28, magia: 14, resistencia: 24, agilidad: 9, suerte: 8 },
    habilidades: ['Ice Boost', 'Debilitate'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/1/13/Lich.jpg/revision/latest?cb=20100617103401' },
  { nombre: 'Incubus', arcana: 'Devil', nivel: 14,
    stats: { fuerza: 6, magia: 16, resistencia: 5, agilidad: 6, suerte: 17 },
    habilidades: ['Marin Karin', 'Garula'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/b/bd/DevSum_Incubus.png/revision/latest?cb=20240511150603' },

  // --- Tower ---
  { nombre: 'Nyarlathotep', arcana: 'Tower', nivel: 85,
    stats: { fuerza: 37, magia: 67, resistencia: 39, agilidad: 29, suerte: 46 },
    habilidades: ['Mudoon', 'Bufu'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/5/5b/Nyarlathotep_%28SMTII_Art%29.png/revision/latest?cb=20211107101833' },
  { nombre: 'Mara', arcana: 'Tower', nivel: 40,
    stats: { fuerza: 15, magia: 26, resistencia: 30, agilidad: 11, suerte: 29 },
    habilidades: ['Hamaon', 'Bufudyne'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/3/37/00146_Mara.png/revision/latest?cb=20220929114111' },
  { nombre: 'Seth (demon)', arcana: 'Tower', nivel: 50,
    stats: { fuerza: 33, magia: 19, resistencia: 27, agilidad: 30, suerte: 27 },
    habilidades: ['Rampage', 'Charge'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/9/93/Seth_in_outer_space.jpg/revision/latest?cb=20191111204945' },
  { nombre: 'Hastur', arcana: 'Tower', nivel: 65,
    stats: { fuerza: 40, magia: 24, resistencia: 26, agilidad: 57, suerte: 24 },
    habilidades: ['Wind Boost', 'Sonic Punch'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/3/3d/P2EP_Hastur.png/revision/latest?cb=20240729015620' },
  { nombre: 'Tezcatlipoca', arcana: 'Tower', nivel: 50,
    stats: { fuerza: 42, magia: 20, resistencia: 34, agilidad: 26, suerte: 13 },
    habilidades: ['Ice Boost', 'Ziodyne'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/9/93/SMTIITezcatlipoca.jpg/revision/latest?cb=20100507004220' },
  { nombre: 'Amatsu Mikaboshi', arcana: 'Tower', nivel: 70,
    stats: { fuerza: 43, magia: 45, resistencia: 45, agilidad: 15, suerte: 36 },
    habilidades: ['Poison Breath', 'Charge'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/7/79/78-Up110-0112.jpg/revision/latest?cb=20120106025526' },
  { nombre: 'Ahriman', arcana: 'Tower', nivel: 60,
    stats: { fuerza: 38, magia: 40, resistencia: 28, agilidad: 38, suerte: 15 },
    habilidades: ['Diarama', 'Vorpal Blade'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/f/f0/AhrimanA2.jpg/revision/latest?cb=20220116105852' },

  // --- Star ---
  { nombre: 'Garuda', arcana: 'Star', nivel: 35,
    stats: { fuerza: 20, magia: 20, resistencia: 13, agilidad: 21, suerte: 25 },
    habilidades: ['Bufu', 'Curse Boost'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/9/9b/00036_Garuda_%28Reupload%29.png/revision/latest?cb=20220525024450' },
  { nombre: 'Freya', arcana: 'Star', nivel: 40,
    stats: { fuerza: 18, magia: 26, resistencia: 17, agilidad: 28, suerte: 21 },
    habilidades: ['Cleave', 'Garu'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/5/5b/Vanadis.png/revision/latest?cb=20241024150407' },
  { nombre: 'Janus', arcana: 'Star', nivel: 25,
    stats: { fuerza: 16, magia: 8, resistencia: 21, agilidad: 8, suerte: 21 },
    habilidades: ['Megido', 'Rakukaja'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/2/2e/297_Janus.jpg/revision/latest?cb=20100515024731' },
  { nombre: 'Kartikeya', arcana: 'Star', nivel: 30,
    stats: { fuerza: 18, magia: 25, resistencia: 18, agilidad: 8, suerte: 17 },
    habilidades: ['Hamaon', 'Ziodyne'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/e/e3/DS_Kartikeya.png/revision/latest?cb=20240620044940' },
  { nombre: 'Sleipnir (demon)', arcana: 'Star', nivel: 22,
    stats: { fuerza: 16, magia: 15, resistencia: 20, agilidad: 8, suerte: 9 },
    habilidades: ['Bufudyne', 'Debilitate'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/7/7f/Sleipnir_%28Dx2%29.png/revision/latest?cb=20221102113230' },
  { nombre: 'Kamui', arcana: 'Star', nivel: 35,
    stats: { fuerza: 7, magia: 9, resistencia: 23, agilidad: 31, suerte: 29 },
    habilidades: ['Rakukaja', 'Dekaja'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/8/88/Kamui.png/revision/latest?cb=20141211080551' },

  // --- Moon ---
  { nombre: 'Artemis', arcana: 'Moon', nivel: 38,
    stats: { fuerza: 25, magia: 12, resistencia: 35, agilidad: 10, suerte: 24 },
    habilidades: ['Diarama', 'Mediarama'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/f/f9/KMT_Artemis.png/revision/latest?cb=20240512235157' },
  { nombre: 'Tsukuyomi', arcana: 'Moon', nivel: 45,
    stats: { fuerza: 24, magia: 28, resistencia: 20, agilidad: 33, suerte: 18 },
    habilidades: ['Elec Boost', 'Tarukaja'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/9/96/00227_Tsukuyomi.png/revision/latest?cb=20220822074648' },
  { nombre: 'Nightmare', arcana: 'Moon', nivel: 20,
    stats: { fuerza: 6, magia: 16, resistencia: 9, agilidad: 16, suerte: 16 },
    habilidades: ['Charge', 'Poison Breath'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/8/85/00062_Nightmare.png/revision/latest?cb=20220727075628' },
  { nombre: 'Kaguya Hime', arcana: 'Moon', nivel: 32,
    stats: { fuerza: 17, magia: 9, resistencia: 21, agilidad: 21, suerte: 25 },
    habilidades: ['Poison Breath', 'Bufu'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/b/ba/Kaguyahime.jpg/revision/latest?cb=20100615120446' },
  { nombre: 'Sandalphon', arcana: 'Moon', nivel: 50,
    stats: { fuerza: 25, magia: 17, resistencia: 48, agilidad: 26, suerte: 19 },
    habilidades: ['Garudyne', 'Charge'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/0/04/Sandalphon_%28Devil_Summoner_Art%29.png/revision/latest?cb=20210912210927' },
  { nombre: 'Hare of Inaba', arcana: 'Moon', nivel: 6,
    stats: { fuerza: 4, magia: 9, resistencia: 7, agilidad: 5, suerte: 4 },
    habilidades: ['Mudo', 'Rampage'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/f/f2/Hare_of_Inaba_%28DS%29.png/revision/latest?cb=20240611112947' },

  // --- Sun ---
  { nombre: 'Apollo', arcana: 'Sun', nivel: 45,
    stats: { fuerza: 14, magia: 30, resistencia: 14, agilidad: 42, suerte: 23 },
    habilidades: ['Garu', 'Endure'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/b/ba/Apollo_KMT.png/revision/latest?cb=20230601200113' },
  { nombre: 'Horus', arcana: 'Sun', nivel: 48,
    stats: { fuerza: 15, magia: 28, resistencia: 13, agilidad: 32, suerte: 43 },
    habilidades: ['Tarukaja', 'Dia'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/e/ea/Horus_%28SMTII_Art%29.png/revision/latest?cb=20220227162936' },
  { nombre: 'Quetzalcoatl', arcana: 'Sun', nivel: 60,
    stats: { fuerza: 13, magia: 40, resistencia: 37, agilidad: 25, suerte: 44 },
    habilidades: ['Bufudyne', 'Bufula'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/a/a5/QuetzalcoatlSMT2.jpg/revision/latest?cb=20080808015446' },
  { nombre: 'Heimdall', arcana: 'Sun', nivel: 38,
    stats: { fuerza: 13, magia: 25, resistencia: 15, agilidad: 12, suerte: 41 },
    habilidades: ['Zio', 'Diarama'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/2/23/Heimdall_%28Dx2_Art%29.png/revision/latest?cb=20220602065246' },
  { nombre: 'Vulcanus', arcana: 'Sun', nivel: 30,
    stats: { fuerza: 9, magia: 13, resistencia: 16, agilidad: 17, suerte: 33 },
    habilidades: ['Charge', 'Cleave'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/a/ae/VulcanusP2.jpg/revision/latest?cb=20131125091023' },
  { nombre: 'Thunderbird', arcana: 'Sun', nivel: 25,
    stats: { fuerza: 6, magia: 13, resistencia: 12, agilidad: 25, suerte: 19 },
    habilidades: ['Zionga', 'Mudo'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/0/0c/SH_Thunderbird.png/revision/latest?cb=20240525065418' },

  // --- Judgement ---
  { nombre: 'Gabriel', arcana: 'Judgement', nivel: 55,
    stats: { fuerza: 45, magia: 12, resistencia: 40, agilidad: 31, suerte: 19 },
    habilidades: ['Mudo', 'Vorpal Blade'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/0/0a/00022_Gabriel.png/revision/latest?cb=20220530041032' },
  { nombre: 'Nike', arcana: 'Judgement', nivel: 35,
    stats: { fuerza: 15, magia: 17, resistencia: 20, agilidad: 22, suerte: 25 },
    habilidades: ['Charge', 'Elec Boost'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/8/8d/Nike_%28P2EP_Art%29.png/revision/latest?cb=20210912231616' },
  { nombre: 'Abaddon', arcana: 'Judgement', nivel: 50,
    stats: { fuerza: 23, magia: 40, resistencia: 25, agilidad: 27, suerte: 21 },
    habilidades: ['Garu', 'Garula'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/7/7f/00077_Abaddon.png/revision/latest?cb=20220731054137' },
  { nombre: 'Trumpeter', arcana: 'Judgement', nivel: 75,
    stats: { fuerza: 22, magia: 57, resistencia: 30, agilidad: 22, suerte: 65 },
    habilidades: ['Megidola', 'Marin Karin'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/5/54/Trumpeter_%28SMTIII_Art%29.png/revision/latest?cb=20210912211218' },
  { nombre: 'Ophanim', arcana: 'Judgement', nivel: 40,
    stats: { fuerza: 24, magia: 23, resistencia: 16, agilidad: 19, suerte: 29 },
    habilidades: ['Dekaja', 'Mind Charge'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/d/d8/253.jpg/revision/latest?cb=20110617125550' },
  { nombre: 'Vohu Manah', arcana: 'Judgement', nivel: 30,
    stats: { fuerza: 25, magia: 24, resistencia: 16, agilidad: 14, suerte: 9 },
    habilidades: ['Garu', 'Charge'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/9/9f/Vohu_Manah_%28Persona_Art%29.png/revision/latest?cb=20210911230533' },
  { nombre: 'Armaiti', arcana: 'Judgement', nivel: 28,
    stats: { fuerza: 18, magia: 8, resistencia: 20, agilidad: 12, suerte: 24 },
    habilidades: ['Hamaon', 'Assault Dive'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/d/d6/Armaiti_%28DSSH_Art%29.png/revision/latest?cb=20210912224709' },

  // --- World ---
  { nombre: 'Leviathan', arcana: 'World', nivel: 65,
    stats: { fuerza: 16, magia: 24, resistencia: 51, agilidad: 45, suerte: 34 },
    habilidades: ['Dekaja', 'Rakukaja'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/4/45/01258_Z%C5%8Dma_Dragon_Type_2.png/revision/latest?cb=20230922051841' },
  { nombre: 'Kraken', arcana: 'World', nivel: 50,
    stats: { fuerza: 19, magia: 26, resistencia: 17, agilidad: 37, suerte: 36 },
    habilidades: ['Dia', 'Bufudyne'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/c/c3/KrakenSMT.jpg/revision/latest?cb=20080803213736' },
  { nombre: 'Ouroboros', arcana: 'World', nivel: 90,
    stats: { fuerza: 58, magia: 62, resistencia: 28, agilidad: 49, suerte: 35 },
    habilidades: ['Garula', 'Mind Charge'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/a/a0/SH_Ourobos.png/revision/latest?cb=20240618032654' },
  { nombre: 'Demeter', arcana: 'World', nivel: 40,
    stats: { fuerza: 14, magia: 33, resistencia: 17, agilidad: 30, suerte: 17 },
    habilidades: ['Elec Boost', 'Curse Boost'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/0/03/Demeter.png/revision/latest?cb=20240623112841' },
  { nombre: 'Izanagi-no-Okami', arcana: 'World', nivel: 95,
    stats: { fuerza: 44, magia: 21, resistencia: 64, agilidad: 54, suerte: 60 },
    habilidades: ['Agilao', 'Sonic Punch'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/6/67/P4-Izanagi-no-Okami.jpg/revision/latest?cb=20090104090157' },
  { nombre: 'Illuyanka', arcana: 'World', nivel: 42,
    stats: { fuerza: 29, magia: 18, resistencia: 40, agilidad: 12, suerte: 17 },
    habilidades: ['Mudo', 'Tarukaja'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/5/50/Illuyanka_%28Dx2_Art%29.png/revision/latest?cb=20210705231954' },
  { nombre: 'Zhu Yin', arcana: 'World', nivel: 60,
    stats: { fuerza: 13, magia: 48, resistencia: 20, agilidad: 33, suerte: 45 },
    habilidades: ['Megidola', 'Agidyne'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/1/14/DDSZhuyin.jpg/revision/latest?cb=20190331041448' },

  // --- Magician ---
  { nombre: 'Faust', arcana: 'Magician', nivel: 20,
    stats: { fuerza: 12, magia: 13, resistencia: 15, agilidad: 9, suerte: 13 },
    habilidades: ['Bufudyne', 'Dia'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/d/d0/Faust.png/revision/latest?cb=20130413064009' },
  { nombre: 'Crowley', arcana: 'Magician', nivel: 35,
    stats: { fuerza: 20, magia: 19, resistencia: 17, agilidad: 23, suerte: 20 },
    habilidades: ['Ziodyne', 'Endure'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/c/c6/KURO.PNG/revision/latest?cb=20120608190158' },

  // --- Lovers ---
  { nombre: 'Lorelei', arcana: 'Lovers', nivel: 15,
    stats: { fuerza: 14, magia: 8, resistencia: 13, agilidad: 8, suerte: 8 },
    habilidades: ['Bufula', 'Vorpal Blade'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/c/c0/DS_Lorelei.png/revision/latest?cb=20240504045629' },
  { nombre: 'Robin Goodfellow', arcana: 'Lovers', nivel: 14,
    stats: { fuerza: 11, magia: 5, resistencia: 13, agilidad: 15, suerte: 5 },
    habilidades: ['Charge', 'Hama'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/b/b3/Robin_Goodfellow.png/revision/latest?cb=20150415074741' },

  // --- HangedMan ---
  { nombre: 'Adramelech', arcana: 'HangedMan', nivel: 42,
    stats: { fuerza: 20, magia: 35, resistencia: 11, agilidad: 21, suerte: 30 },
    habilidades: ['Cleave', 'Poison Breath'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/c/cd/Adramelech_SMTIVF.png/revision/latest?cb=20211111062948' },

  // --- Star ---
  { nombre: 'Hoenir', arcana: 'Star', nivel: 28,
    stats: { fuerza: 11, magia: 14, resistencia: 14, agilidad: 24, suerte: 19 },
    habilidades: ['Bufudyne', 'Garudyne'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/a/ab/Hoenir_IS.png/revision/latest?cb=20140823002154' },

  // --- Moon ---
  { nombre: 'Alraune', arcana: 'Moon', nivel: 10,
    stats: { fuerza: 8, magia: 8, resistencia: 7, agilidad: 9, suerte: 9 },
    habilidades: ['Megido', 'Mediarama'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/6/6c/Alraune_%28SMTII_Art%29.jpg/revision/latest?cb=20210624003144' },

  // --- Sun ---
  { nombre: 'Surya', arcana: 'Sun', nivel: 40,
    stats: { fuerza: 26, magia: 23, resistencia: 21, agilidad: 26, suerte: 15 },
    habilidades: ['Bufudyne', 'Garula'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/0/0b/Surya.png/revision/latest?cb=20150415081321' },

  // --- World ---
  { nombre: 'Njord', arcana: 'World', nivel: 30,
    stats: { fuerza: 21, magia: 13, resistencia: 19, agilidad: 15, suerte: 19 },
    habilidades: ['Dekaja', 'Debilitate'],
    imagenUrl: 'https://static.wikia.nocookie.net/megamitensei/images/b/b5/Njord_IS.png/revision/latest?cb=20150322200504' },

];

async function seed() {
  await connectDB();
  await Persona.deleteMany({});
  await Persona.insertMany(personas);
  console.log(`[seed] ${personas.length} Personas insertadas`);
  await mongoose.disconnect();
}

seed().catch((err) => {
  console.error('[seed] error:', err);
  process.exit(1);
});
